export default [
  {
    login: "mdziedzinski",
    id: 65560435,
    node_id: "MDQ6VXNlcjY1NTYwNDM1",
    avatar_url: "https://avatars.githubusercontent.com/u/65560435?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mdziedzinski",
    html_url: "https://github.com/mdziedzinski",
    followers_url: "https://api.github.com/users/mdziedzinski/followers",
    following_url:
      "https://api.github.com/users/mdziedzinski/following{/other_user}",
    gists_url: "https://api.github.com/users/mdziedzinski/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mdziedzinski/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mdziedzinski/subscriptions",
    organizations_url: "https://api.github.com/users/mdziedzinski/orgs",
    repos_url: "https://api.github.com/users/mdziedzinski/repos",
    events_url: "https://api.github.com/users/mdziedzinski/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mdziedzinski/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wiewiex",
    id: 92727287,
    node_id: "U_kgDOBYbn9w",
    avatar_url: "https://avatars.githubusercontent.com/u/92727287?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wiewiex",
    html_url: "https://github.com/wiewiex",
    followers_url: "https://api.github.com/users/wiewiex/followers",
    following_url:
      "https://api.github.com/users/wiewiex/following{/other_user}",
    gists_url: "https://api.github.com/users/wiewiex/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wiewiex/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wiewiex/subscriptions",
    organizations_url: "https://api.github.com/users/wiewiex/orgs",
    repos_url: "https://api.github.com/users/wiewiex/repos",
    events_url: "https://api.github.com/users/wiewiex/events{/privacy}",
    received_events_url: "https://api.github.com/users/wiewiex/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ellianel",
    id: 104525124,
    node_id: "U_kgDOBjrtRA",
    avatar_url: "https://avatars.githubusercontent.com/u/104525124?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ellianel",
    html_url: "https://github.com/Ellianel",
    followers_url: "https://api.github.com/users/Ellianel/followers",
    following_url:
      "https://api.github.com/users/Ellianel/following{/other_user}",
    gists_url: "https://api.github.com/users/Ellianel/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ellianel/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ellianel/subscriptions",
    organizations_url: "https://api.github.com/users/Ellianel/orgs",
    repos_url: "https://api.github.com/users/Ellianel/repos",
    events_url: "https://api.github.com/users/Ellianel/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ellianel/received_events",
    type: "User",
    site_admin: false,
  },
];
