export default {
  login: "luckiMoH",
  id: 104385016,
  node_id: "U_kgDOBjjJ-A",
  avatar_url: "https://avatars.githubusercontent.com/u/104385016?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/luckiMoH",
  html_url: "https://github.com/luckiMoH",
  followers_url: "https://api.github.com/users/luckiMoH/followers",
  following_url: "https://api.github.com/users/luckiMoH/following{/other_user}",
  gists_url: "https://api.github.com/users/luckiMoH/gists{/gist_id}",
  starred_url: "https://api.github.com/users/luckiMoH/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/luckiMoH/subscriptions",
  organizations_url: "https://api.github.com/users/luckiMoH/orgs",
  repos_url: "https://api.github.com/users/luckiMoH/repos",
  events_url: "https://api.github.com/users/luckiMoH/events{/privacy}",
  received_events_url: "https://api.github.com/users/luckiMoH/received_events",
  type: "User",
  site_admin: false,
  name: "Mateusz Majewski",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Front end developer and testing engineer.\r\nUsing HTML, CSS, SASS, JavaScript, Node.js, React, Redux, Python, Robot Framework.\r\nWilling to learn more and more. ",
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 3,
  following: 3,
  created_at: "2022-04-25T17:47:22Z",
  updated_at: "2023-04-20T08:12:19Z",
};
